wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1684309074.429724
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.0
      5: 0.15.2
      8:
      - 2
      - 3
      - 5
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
val_percent:
  desc: null
  value: 0.1
save_checkpoint:
  desc: null
  value: true
img_scale:
  desc: null
  value: 0.25
amp:
  desc: null
  value: true
